# Site settings
title: Rod Machen
email: mail@rodmachen.com
description: > # this means to ignore newlines until "baseurl:"
  Rod Machen's writings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodmachen.com" # the base hostname & protocol for your site
twitter_username: rodmachen
plugins: [jekyll-paginate]
# Build settings
markdown: kramdown

permalink: /:categories/:title/

paginate: 10
paginate_path: "/archive/page:num/"

exclude:
 - code.rodmachen.com/
 - photo.rodmachen.com/
 - s3_website.yml